import Head from 'next/head';
import Slide from '../components/slider';
import AboutUs from '../components/about';
import Team from '../components/team';
import ContactComp from '../components/contact';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<Slide />
			<AboutUs />
			<Team />
			<ContactComp />
		</div>
	);
}
